swagger: "2.0"
info:
  description: 吐槽
  version: "1.0.0"
  title: API-吐槽
host: localhost:9006
basePath: /spit
paths:
  /spit:
    post:
      summary: 增加吐槽
      parameters:
      - in: body
        name: body
        description: Spit实体
        required: true
        schema:
          $ref: "#/definitions/Spit"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: Spit全部列表
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiSpitListResponse'
  /spit/{spitId}:
    get:
      summary: 根据ID查询吐槽
      parameters:
        - name: spitId
          in: path
          description: SpitID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiSpitResponse'
    put:
      summary: 修改吐槽
      parameters:
        - name: spitId
          in: path
          description: SpitID
          required: true
          type: string
        - name: body
          in: body
          description: Spit实体
          required: true
          schema:
            $ref: "#/definitions/Spit"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除吐槽
      parameters:
        - name: spitId
          in: path
          description: SpitID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /spit/thumbup/{spitId}:
    put:
      summary: 吐槽点赞
      parameters:
        - name: spitId
          in: path
          description: SpitID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /spit/search:
    post:
      summary: 根据条件查询Spit列表
      parameters:
        - name: body
          in: body
          description: Spit实体类
          required: true
          schema:
            $ref: '#/definitions/Spit'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiSpitListResponse'
  /spit/search/{page}/{size}:
    post:
      summary: Spit分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/Spit"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiSpitPageResponse'
  /spit/comment/{parentid}/{page}/{size}:
    get:
      summary: 根据上级ID查询吐槽数据（分页）
      parameters:
        - name: parentid
          in: path
          description: 上级吐槽ID
          required: true
          type: string
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiSpitPageResponse'
definitions:
  Spit:
    type: "object"
    properties:
      _id:
        type: "string"
        description: "ID"
      content:
        type: "string"
        description: "吐槽内容"
      publishtime:
        type: "string"
        description: "发布日期"
        format: "date"
      userid:
        type: "string"
        description: "发布人ID"
      nickname:
        type: "string"
        description: "发布人昵称"
      visits:
        type: "integer"
        format: "int32"
        description: "浏览量"
      thumbup:
        type: "integer"
        format: "int32"
        description: "点赞数"
      share:
        type: "integer"
        format: "int32"
        description: "分享数"
      comment:
        type: "integer"
        format: "int32"
        description: "回复数"
      state:
        type: "string"
        description: "是否可见"
      parentid:
        type: "string"
        description: "上级ID"

  SpitList:
    type: "array"
    items:
      $ref: '#/definitions/Spit'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiSpitResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/Spit'
  ApiSpitListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/SpitList'
  ApiSpitPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/SpitList'
